name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean package

    - name: Run tests
      run: mvn test

    - name: Build Docker image
      run: docker build -t ns-service-knowledge .

    - name: Test Docker image
      run: |
        docker run -d --name test-container -p 8080:8080 ns-service-knowledge
        sleep 10
        docker logs test-container
        curl -X POST 'http://localhost:8080/api/v1/SMSnotifications' -H 'Content-Type: application/json' -d '{"fromNumber":"${{ secrets.TWILIO_PHONE_NUMBER }}","toNumber":"+919027652516","message":"Test SMS from CI"}'
        docker stop test-container
        docker rm test-container
